# Generated by Django 6.0.2 on 2026-03-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.RemoveField(
            model_name='associado',
            name='data_filiacao',
        ),
        migrations.AddField(
            model_name='associado',
            name='empresa',
            field=models.CharField(default='Não informada', max_length=100),
        ),
        migrations.AlterField(
            model_name='associado',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='associado',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='associado',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='associado',
            table='associado',
        ),
    ]
