# Generated by Django 6.0.2 on 2026-03-31 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0002_empresa_remove_associado_data_filiacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associado.empresa'),
        ),
    ]
